package Ventanas;

import interfaz.principal;
import java.awt.Color;
import javax.swing.JOptionPane;
import java.sql.*;
import java.time.LocalDate;
import java.time.Period;
import java.time.format.DateTimeFormatter;

public class ventanaRegistrarNombres extends javax.swing.JFrame {

    public ventanaRegistrarNombres() {
        initComponents();
        this.setLocationRelativeTo(null);    
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel17 = new javax.swing.JPanel();
        txt_nombre = new javax.swing.JTextField();
        numDNI = new javax.swing.JTextField();
        txt_apellido = new javax.swing.JTextField();
        registrarEmpleado11 = new javax.swing.JButton();
        txt_direccion = new javax.swing.JTextField();
        txt_telefono = new javax.swing.JTextField();
        txt_ncuenta = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        registrarEmpleado1 = new javax.swing.JButton();
        buscarempleado = new javax.swing.JButton();
        BotonMenu1 = new javax.swing.JButton();
        salir = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        fechaalta1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        fechabaja1 = new javax.swing.JTextField();
        puesto = new javax.swing.JLabel();
        Contrato1 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        fechaalta2 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        fechabaja2 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        categoria = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel17.setBackground(new java.awt.Color(216, 243, 220));
        jPanel17.setPreferredSize(new java.awt.Dimension(617, 516));
        jPanel17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_nombre.setBackground(new java.awt.Color(216, 243, 220));
        txt_nombre.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        txt_nombre.setForeground(new java.awt.Color(0, 0, 0));
        txt_nombre.setText("INTRODUCIR NOMBRE");
        txt_nombre.setToolTipText("NOMBRE");
        txt_nombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_nombreMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                txt_nombreMouseReleased(evt);
            }
        });
        txt_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nombreActionPerformed(evt);
            }
        });
        jPanel17.add(txt_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 84, 230, 40));

        numDNI.setBackground(new java.awt.Color(216, 243, 220));
        numDNI.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        numDNI.setForeground(new java.awt.Color(0, 0, 0));
        numDNI.setText("INTRODUCIR DNI");
        numDNI.setToolTipText(" DNI");
        numDNI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                numDNIMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                numDNIMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                numDNIMousePressed(evt);
            }
        });
        numDNI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numDNIActionPerformed(evt);
            }
        });
        jPanel17.add(numDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 230, 40));

        txt_apellido.setBackground(new java.awt.Color(216, 243, 220));
        txt_apellido.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        txt_apellido.setForeground(new java.awt.Color(0, 0, 0));
        txt_apellido.setText("INTRODUCIR APELLIDO");
        txt_apellido.setToolTipText("APELLIDO");
        txt_apellido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_apellidoMousePressed(evt);
            }
        });
        txt_apellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_apellidoActionPerformed(evt);
            }
        });
        jPanel17.add(txt_apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 230, 42));

        registrarEmpleado11.setBackground(new java.awt.Color(183, 228, 199));
        registrarEmpleado11.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        registrarEmpleado11.setForeground(new java.awt.Color(0, 0, 0));
        registrarEmpleado11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/contrato (2).png"))); // NOI18N
        registrarEmpleado11.setText("Registrar ");
        registrarEmpleado11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(159, 223, 188)));
        registrarEmpleado11.setContentAreaFilled(false);
        registrarEmpleado11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        registrarEmpleado11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        registrarEmpleado11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                registrarEmpleado11MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                registrarEmpleado11MouseExited(evt);
            }
        });
        registrarEmpleado11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarEmpleado2ActionPerformed(evt);
            }
        });
        jPanel17.add(registrarEmpleado11, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 440, 120, -1));

        txt_direccion.setBackground(new java.awt.Color(216, 243, 220));
        txt_direccion.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        txt_direccion.setForeground(new java.awt.Color(0, 0, 0));
        txt_direccion.setText("INTRODUCIR DIRECCION");
        txt_direccion.setToolTipText("DIRECCION");
        txt_direccion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_direccionMousePressed(evt);
            }
        });
        txt_direccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_apellido1ActionPerformed(evt);
            }
        });
        jPanel17.add(txt_direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 320, 230, 42));

        txt_telefono.setBackground(new java.awt.Color(216, 243, 220));
        txt_telefono.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        txt_telefono.setForeground(new java.awt.Color(0, 0, 0));
        txt_telefono.setText("INTRODUCIR TELEFONO");
        txt_telefono.setToolTipText("TELEFONO");
        txt_telefono.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_telefonoMousePressed(evt);
            }
        });
        txt_telefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_apellido2ActionPerformed(evt);
            }
        });
        jPanel17.add(txt_telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, 230, 42));

        txt_ncuenta.setBackground(new java.awt.Color(216, 243, 220));
        txt_ncuenta.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        txt_ncuenta.setForeground(new java.awt.Color(0, 0, 0));
        txt_ncuenta.setText("INTRODUCIR NUMERO DE CUENTA");
        txt_ncuenta.setToolTipText("NUMERO CUENTA");
        txt_ncuenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_ncuentaMousePressed(evt);
            }
        });
        txt_ncuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_apellido3ActionPerformed(evt);
            }
        });
        jPanel17.add(txt_ncuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 380, 230, 42));

        jPanel2.setBackground(new java.awt.Color(159, 223, 188));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/derechos-de-autor.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("PROGRAMA PARA LA GESTION DE NOMINAS DE EMPLEADOS");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );

        jPanel17.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, -1));

        jPanel3.setBackground(new java.awt.Color(183, 228, 199));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/perfil.png"))); // NOI18N

        registrarEmpleado1.setBackground(new java.awt.Color(153, 51, 0));
        registrarEmpleado1.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        registrarEmpleado1.setForeground(new java.awt.Color(255, 255, 255));
        registrarEmpleado1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/contrato (2).png"))); // NOI18N
        registrarEmpleado1.setText("Registrar Empleado");
        registrarEmpleado1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(216, 243, 220)));
        registrarEmpleado1.setContentAreaFilled(false);
        registrarEmpleado1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        registrarEmpleado1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        registrarEmpleado1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                registrarEmpleado1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                registrarEmpleado1MouseExited(evt);
            }
        });
        registrarEmpleado1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarEmpleado1ActionPerformed(evt);
            }
        });

        buscarempleado.setBackground(new java.awt.Color(183, 228, 199));
        buscarempleado.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        buscarempleado.setForeground(new java.awt.Color(255, 255, 255));
        buscarempleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/usuario.png"))); // NOI18N
        buscarempleado.setText("    Buscar Empleado");
        buscarempleado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(216, 243, 220)));
        buscarempleado.setContentAreaFilled(false);
        buscarempleado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buscarempleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buscarempleadoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buscarempleadoMouseExited(evt);
            }
        });
        buscarempleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarempleadoActionPerformed(evt);
            }
        });

        BotonMenu1.setBackground(new java.awt.Color(183, 228, 199));
        BotonMenu1.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        BotonMenu1.setForeground(new java.awt.Color(255, 255, 255));
        BotonMenu1.setText("MENU PRINCIPAL");
        BotonMenu1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(216, 243, 220)));
        BotonMenu1.setContentAreaFilled(false);
        BotonMenu1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotonMenu1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotonMenu1MouseExited(evt);
            }
        });
        BotonMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonMenu1ActionPerformed(evt);
            }
        });

        salir.setBackground(new java.awt.Color(183, 228, 199));
        salir.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        salir.setForeground(new java.awt.Color(255, 255, 255));
        salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/atajo.png"))); // NOI18N
        salir.setText("              Salir");
        salir.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(216, 243, 220)));
        salir.setContentAreaFilled(false);
        salir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                salirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                salirMouseExited(evt);
            }
        });
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(buscarempleado, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(BotonMenu1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(salir, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(registrarEmpleado1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 2, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(BotonMenu1)
                .addGap(12, 12, 12)
                .addComponent(registrarEmpleado1)
                .addGap(18, 18, 18)
                .addComponent(buscarempleado, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(salir)
                .addGap(70, 70, 70))
        );

        jPanel17.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 38, -1, 450));

        jLabel4.setFont(new java.awt.Font("DialogInput", 3, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Registrar Datos De Empleado");
        jPanel17.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 50, -1, -1));

        jLabel6.setFont(new java.awt.Font("DialogInput", 0, 14)); // NOI18N
        jLabel6.setText("fecha de alta ");
        jPanel17.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, 30));

        jLabel7.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("FECHA ALTA");
        jPanel17.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 80, 80, 40));

        fechaalta1.setBackground(new java.awt.Color(216, 243, 220));
        fechaalta1.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        fechaalta1.setForeground(new java.awt.Color(0, 0, 0));
        fechaalta1.setText("año-mes-dia");
        fechaalta1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                fechaalta1MousePressed(evt);
            }
        });
        fechaalta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fechaalta1ActionPerformed(evt);
            }
        });
        jPanel17.add(fechaalta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 80, 170, 40));

        jLabel8.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("FECHA BAJA");
        jPanel17.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 140, 80, 40));

        fechabaja1.setBackground(new java.awt.Color(216, 243, 220));
        fechabaja1.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        fechabaja1.setForeground(new java.awt.Color(0, 0, 0));
        fechabaja1.setText("año-mes-dia");
        fechabaja1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                fechabaja1MousePressed(evt);
            }
        });
        fechabaja1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fechabaja1ActionPerformed(evt);
            }
        });
        jPanel17.add(fechabaja1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 140, 170, 40));

        puesto.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        puesto.setForeground(new java.awt.Color(0, 0, 0));
        puesto.setText("PUESTO");
        jPanel17.add(puesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 200, 70, 30));

        Contrato1.setBackground(new java.awt.Color(216, 243, 220));
        Contrato1.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        Contrato1.setForeground(new java.awt.Color(0, 0, 0));
        Contrato1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jefe", "Gerente", "Coordinador", "Encargado" }));
        jPanel17.add(Contrato1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 200, 170, -1));

        jLabel5.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("FECHA ALTA");
        jPanel17.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 260, 80, 40));

        fechaalta2.setBackground(new java.awt.Color(216, 243, 220));
        fechaalta2.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        fechaalta2.setForeground(new java.awt.Color(0, 0, 0));
        fechaalta2.setText("año-mes-dia");
        fechaalta2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                fechaalta2MousePressed(evt);
            }
        });
        fechaalta2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fechaalta2ActionPerformed(evt);
            }
        });
        jPanel17.add(fechaalta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 260, 170, 40));

        jLabel9.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("FECHA BAJA");
        jPanel17.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 320, 90, 40));

        fechabaja2.setBackground(new java.awt.Color(216, 243, 220));
        fechabaja2.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        fechabaja2.setForeground(new java.awt.Color(0, 0, 0));
        fechabaja2.setText("año-mes-dia");
        fechabaja2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                fechabaja2MousePressed(evt);
            }
        });
        fechabaja2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fechabaja2ActionPerformed(evt);
            }
        });
        jPanel17.add(fechabaja2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 320, 170, 40));

        jLabel10.setBackground(new java.awt.Color(0, 0, 0));
        jLabel10.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("CATEGORIA");
        jPanel17.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 380, 90, 40));

        categoria.setBackground(new java.awt.Color(216, 243, 220));
        categoria.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        categoria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                categoriaMousePressed(evt);
            }
        });
        categoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoriaActionPerformed(evt);
            }
        });
        jPanel17.add(categoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 380, 170, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel17, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_apellido3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_apellido3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_apellido3ActionPerformed

    private void txt_ncuentaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_ncuentaMousePressed
        txt_ncuenta.setText("");
    }//GEN-LAST:event_txt_ncuentaMousePressed

    private void txt_apellido2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_apellido2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_apellido2ActionPerformed

    private void txt_telefonoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_telefonoMousePressed
        txt_telefono.setText("");
    }//GEN-LAST:event_txt_telefonoMousePressed

    private void txt_apellido1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_apellido1ActionPerformed

    }//GEN-LAST:event_txt_apellido1ActionPerformed

    private void txt_direccionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_direccionMousePressed
        txt_direccion.setText("");
    }//GEN-LAST:event_txt_direccionMousePressed

    private void registrarEmpleado2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarEmpleado2ActionPerformed

        String fecha1= fechaalta1.getText();
        String fecha2= fechabaja1.getText();
        String fecha3= fechaalta2.getText();
        String fecha4= fechabaja2.getText();
        
        LocalDate d1 = LocalDate.parse( fecha1, DateTimeFormatter.ISO_LOCAL_DATE);  
        LocalDate d2 = LocalDate.parse( fecha2, DateTimeFormatter.ISO_LOCAL_DATE);
        LocalDate d3 = LocalDate.parse( fecha3, DateTimeFormatter.ISO_LOCAL_DATE);  
        LocalDate d4 = LocalDate.parse( fecha4, DateTimeFormatter.ISO_LOCAL_DATE);
            
        Period period = Period.between(d1, d2);
        Period period1 = Period.between(d3, d4);
        
        
        int años = Math.abs(period.getYears());
        int meses = Math.abs(period.getMonths());
        int dias = Math.abs(period.getDays());
        
        int añosc = Math.abs(period1.getYears());
        int mesesc = Math.abs(period1.getMonths());
        int diasc = Math.abs(period1.getDays());
        
        
        
        String Contra = Contrato1.getSelectedItem().toString();
        
        int salario = 0;
        double irpf = 0;
        int trienios = 0;
        double salariot = 0.0;
        

        if( Contra.equalsIgnoreCase("Jefe")){
            salario = 550000;
            irpf = salario * 0.43;
        }
        if( Contra.equalsIgnoreCase("Gerente")){
            salario = 450000;
            irpf = salario * 0.37;
        }
        if( Contra.equalsIgnoreCase("Coordinador")){
            salario = 250000;
            irpf = salario * 0.28;
        }
        if( Contra.equalsIgnoreCase("Encargado")){
            salario = 150000;
            irpf = salario * 0.24;
        }
        System.out.println("Salario Mensual: " + salario + "$ pesos");
        if(años >= 3){
            
            trienios = salario * 5 / 100;
            System.out.println("Complemento De Trienios: " + trienios + "aumeta 5 porciento del salario cada tres años pasados. ");

        }
        System.out.println("Tiempo De Puesto: " + añosc + " AÑOS " + mesesc + " MESES " + diasc + " DIAS ");
        
        double ss = salario * 4.7 / 100;
        double desempleo = salario * 2.8 / 100;
        double formacionp = salario * 3.6 / 100;
        
        System.out.println("Aportaciones a la s.s: " + ss + "$ pesos");
        System.out.println("Desempleo: " + desempleo + "$ pesos");
        System.out.println("Formacion Profecional: " + formacionp + "$ pesos");
        System.out.println("IRPF: " + irpf + "$ pesos");
        System.out.println("contra:" + Contra);
        
        salariot = salario + ss + desempleo + formacionp + irpf ;
        
        System.out.println("Salario Mensual + Complementos : " + salariot + "$ pesos");
        
        try {
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/registros", "root", "");
            PreparedStatement pst = cn.prepareStatement("insert into empleados values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)");

            pst.setString(1,numDNI.getText().trim()); 
            pst.setString(2,txt_nombre.getText().trim());
            pst.setString(3,txt_apellido.getText().trim());
            pst.setString(4,txt_telefono.getText().trim());
            pst.setString(5,txt_direccion.getText());
            pst.setString(6,txt_ncuenta.getText().trim());
            pst.setString(7,Contra.trim());
            pst.setString(8,categoria.getText().trim());
            pst.setInt(9,años);
            pst.setInt(10,meses);
            pst.setInt(11,dias);
            pst.setDouble(12,ss);
            pst.setDouble(13,desempleo);
            pst.setDouble(14,formacionp);
            pst.setDouble(15,salariot);
            pst.executeUpdate();

            numDNI.setText("INTRODUCIR DNI");
            txt_nombre.setText("INTRODUCIR NOMBRE");
            txt_apellido.setText("INTRODUCIR APELLIDO");
            txt_telefono.setText("INTRODUCIR TELEFONO");
            txt_direccion.setText("INTRODUCIR DIRECCION");
            txt_ncuenta.setText("INTRODUCIR NUMERO DE CUENTA");
            categoria.setText("");
            fechaalta1.setText("año-mes-dia");
            fechabaja1.setText("año-mes-dia");
            fechaalta2.setText("año-mes-dia");
            fechabaja2.setText("año-mes-dia");
            
            JOptionPane.showMessageDialog(null, "Registro Exitoso");
            
        } catch (Exception e) {

        }

        
        
    }//GEN-LAST:event_registrarEmpleado2ActionPerformed

    private void registrarEmpleado11MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registrarEmpleado11MouseExited
        registrarEmpleado11.setForeground(Color.WHITE);
    }//GEN-LAST:event_registrarEmpleado11MouseExited

    private void registrarEmpleado11MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registrarEmpleado11MouseEntered
        registrarEmpleado11.setForeground(Color.BLACK);
    }//GEN-LAST:event_registrarEmpleado11MouseEntered

    private void txt_apellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_apellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_apellidoActionPerformed

    private void txt_apellidoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_apellidoMousePressed
        txt_apellido.setText("");
    }//GEN-LAST:event_txt_apellidoMousePressed

    private void numDNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numDNIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numDNIActionPerformed

    private void numDNIMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_numDNIMousePressed
        numDNI.setText("");
    }//GEN-LAST:event_numDNIMousePressed

    private void numDNIMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_numDNIMouseExited

    }//GEN-LAST:event_numDNIMouseExited

    private void numDNIMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_numDNIMouseEntered

    }//GEN-LAST:event_numDNIMouseEntered

    private void txt_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nombreActionPerformed

    private void txt_nombreMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_nombreMousePressed
        txt_nombre.setText("");
    }//GEN-LAST:event_txt_nombreMousePressed

    private void registrarEmpleado1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registrarEmpleado1MouseEntered
        registrarEmpleado1.setForeground(Color.BLACK);        // TODO add your handling code here:
    }//GEN-LAST:event_registrarEmpleado1MouseEntered

    private void registrarEmpleado1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registrarEmpleado1MouseExited
        registrarEmpleado1.setForeground(Color.WHITE);        // TODO add your handling code here:
    }//GEN-LAST:event_registrarEmpleado1MouseExited

    private void registrarEmpleado1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarEmpleado1ActionPerformed

        ventanaRegistrarNombres vr = new ventanaRegistrarNombres();
        vr.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_registrarEmpleado1ActionPerformed

    private void buscarempleadoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buscarempleadoMouseEntered
        buscarempleado.setForeground(Color.BLACK);
    }//GEN-LAST:event_buscarempleadoMouseEntered

    private void buscarempleadoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buscarempleadoMouseExited
        buscarempleado.setForeground(Color.WHITE);        
    }//GEN-LAST:event_buscarempleadoMouseExited

    private void buscarempleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarempleadoActionPerformed
        ventanabuscar b = new ventanabuscar();

        b.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_buscarempleadoActionPerformed

    private void BotonMenu1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonMenu1MouseEntered
        BotonMenu1.setForeground(Color.BLACK);
    }//GEN-LAST:event_BotonMenu1MouseEntered

    private void BotonMenu1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonMenu1MouseExited
        BotonMenu1.setForeground(Color.WHITE);
    }//GEN-LAST:event_BotonMenu1MouseExited

    private void BotonMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonMenu1ActionPerformed
        principal c = new principal();

        c.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BotonMenu1ActionPerformed

    private void salirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirMouseEntered
        salir.setForeground(Color.BLACK);        // TODO add your handling code here:
    }//GEN-LAST:event_salirMouseEntered

    private void salirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirMouseExited
        salir .setForeground(Color.WHITE);     // TODO add your handling code here:
    }//GEN-LAST:event_salirMouseExited

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_salirActionPerformed

    private void fechaalta1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fechaalta1MousePressed
        fechaalta1.setText("");
    }//GEN-LAST:event_fechaalta1MousePressed

    private void fechaalta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fechaalta1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fechaalta1ActionPerformed

    private void fechabaja1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fechabaja1MousePressed
        fechabaja1.setText("");
    }//GEN-LAST:event_fechabaja1MousePressed

    private void fechabaja1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fechabaja1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fechabaja1ActionPerformed

    private void fechaalta2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fechaalta2MousePressed
       fechaalta2.setText("");
    }//GEN-LAST:event_fechaalta2MousePressed

    private void fechaalta2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fechaalta2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fechaalta2ActionPerformed

    private void fechabaja2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fechabaja2MousePressed
        fechabaja2.setText("");
    }//GEN-LAST:event_fechabaja2MousePressed

    private void fechabaja2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fechabaja2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fechabaja2ActionPerformed

    private void categoriaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_categoriaMousePressed

    }//GEN-LAST:event_categoriaMousePressed

    private void categoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_categoriaActionPerformed

    private void txt_nombreMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_nombreMouseReleased

    }//GEN-LAST:event_txt_nombreMouseReleased





    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ventanaRegistrarNombres().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonMenu1;
    private javax.swing.JComboBox<String> Contrato1;
    private javax.swing.JButton buscarempleado;
    private javax.swing.JTextField categoria;
    private javax.swing.JTextField fechaalta1;
    private javax.swing.JTextField fechaalta2;
    private javax.swing.JTextField fechabaja1;
    private javax.swing.JTextField fechabaja2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField numDNI;
    private javax.swing.JLabel puesto;
    private javax.swing.JButton registrarEmpleado1;
    private javax.swing.JButton registrarEmpleado11;
    private javax.swing.JButton salir;
    private javax.swing.JTextField txt_apellido;
    private javax.swing.JTextField txt_direccion;
    private javax.swing.JTextField txt_ncuenta;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_telefono;
    // End of variables declaration//GEN-END:variables
}
